apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fusion-rhoai-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/the-dev-collection/Fusion-AI.git
    targetRevision: main
    path: fusion-openshift-ai/gitops/operator

  destination:
    server: https://kubernetes.default.svc
    namespace: redhat-ods-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  ignoreDifferences:
    - group: operators.coreos.com
      kind: ClusterServiceVersion
      jsonPointers:
        - /status