apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

# patches:
#   - target:
#       kind: ConfigMap
#       name: argocd-cm
#       namespace: openshift-gitops
#     path: argocd-health-patch.yaml

patchesStrategicMerge:
  - argocd-health-patch.yaml